### ISSUE TITLE
NET::ERR_CERT_INVALID on WebTorrent.io

### ISSUE THREAD

**Issue by soer7022** [webtorrent/webtorrent.io#159]
https://webtorrent.io/ does not work, please fix your certificate...

**Comment by soer7022** [comment]
This is not fixed...

**Comment by sashahilton00** [comment]
It is fixed.

**Comment by soer7022** [comment]
It is not fixed.

**Comment by sashahilton00** [comment]
![image](https://user-images.githubusercontent.com/4185362/97437998-237b6480-191c-11eb-82a6-447bbc73c42f.png)

It is fixed.

**Comment by soer7022** [comment]
<img width="986" alt="Screenshot 2020-10-28 at 13 51 16" src="https://user-images.githubusercontent.com/17567175/97438163-b6200180-1924-11eb-9bdc-0cddf4fa9a62.png">
It is not fixed.

**Comment by sashahilton00** [comment]
Flush cache and restart?

**Comment by feross** [comment]
@soer7022 This works for everyone but you. Can you share more information about the error by expanding the "Advanced" section in your Chrome?
